# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.cache/wt [current_project]
set_property parent.project_path C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.srcs/sources_1/new/Divider.sv
  C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.srcs/sources_1/new/timeProvider.sv
  C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.srcs/sources_1/new/SevenSeg.sv
  C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.srcs/sources_1/new/Matrix.sv
  C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.srcs/sources_1/new/disp.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.srcs/constrs_1/new/cs.xdc
set_property used_in_implementation false [get_files C:/Users/User/Desktop/BILKENT/cs223/FinalProject/project_1finexp/project_1finexp.srcs/constrs_1/new/cs.xdc]


synth_design -top disp -part xc7a35tcpg236-1


write_checkpoint -force -noxdef disp.dcp

catch { report_utilization -file disp_utilization_synth.rpt -pb disp_utilization_synth.pb }
